"""First-run setup helpers for deployable Ollama Command Deck installs."""

from __future__ import annotations

import os
import shutil
from pathlib import Path

from .config import get_config_file, get_data_dir


WARNING_TEXT = (
    "Warning: enabling local commands, SSH, hooks, MCP tools, or writable workspaces allows "
    "the AI-assisted app to run actions on this computer or configured devices. Incorrect "
    "commands or tool calls can delete files, change system state, expose data, interrupt "
    "services, or damage remote devices. Only enable tools you understand, restrict the "
    "working directory, and review actions before using them."
)


def _quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_first_run_config(
    *,
    ollama_url: str,
    ollama_api_key: str,
    work_dir: str,
    enable_ssh: bool,
    enable_local: bool,
    enable_search: bool,
    enable_mcp: bool,
    dangerous_mode: bool = False,
    piper_url: str = "",
    searxng_url: str = "",
    brave_api_key: str = "",
    ssh_config_path: str = "/data/.ssh/config",
    ssh_known_hosts_path: str = "/data/.ssh/known_hosts",
    auth_enabled: bool = True,
) -> None:
    config_path = get_config_file()
    config_path.parent.mkdir(parents=True, exist_ok=True)
    data_dir = os.environ.get("OLLAMA_HOOKS_DATA_DIR", "/data")
    key_path = config_path.parent / "ollama_api_key"
    if ollama_api_key:
        key_path.write_text(ollama_api_key.strip() + "\n", encoding="utf-8")
        try:
            os.chmod(key_path, 0o600)
        except OSError:
            pass
        key_file = str(key_path)
    else:
        key_file = ""

    text = f"""# Generated by Ollama Command Deck first-run setup.

[setup]
completed = true
version = 1

[auth]
enabled = {str(auth_enabled).lower()}
skip_login = {str(not auth_enabled).lower()}
session_secret_file = {_quote(str(config_path.parent / "session_secret"))}
users_file = {_quote(str(Path(data_dir) / "users.json"))}
cookie_secure = false
cookie_same_site = "Lax"
session_ttl_hours = 24

[paths]
data_dir = {_quote(data_dir)}
work_dir = {_quote(work_dir)}
allow_work_dir_writes = true
dangerous_mode = {str(dangerous_mode).lower()}

[ollama]
url = {_quote(ollama_url.rstrip("/"))}
api_key_file = {_quote(str(key_file)) if str(key_file) else '""'}

[web]
host = "0.0.0.0"
port = 8765
cert_file = ""
key_file = ""

[tts]
piper_url = {_quote(piper_url.rstrip("/"))}

[search]
searxng_url = {_quote(searxng_url.rstrip("/"))}
brave_api_key = {_quote(brave_api_key)}

[tools]
local_command = {str(enable_local).lower()}
ssh_command = {str(enable_ssh).lower()}
internet_search = {str(enable_search).lower()}
current_datetime = true
ollama_models = true
monitoring = false

[mcp]
enabled = {str(enable_mcp).lower()}
server_enabled = {str(enable_mcp).lower()}

[hooks]
enabled = true
run_local = {str(enable_local).lower()}
run_ssh = {str(enable_ssh).lower()}
search_web = {str(enable_search).lower()}
current_time = true

[skills]
enabled = true
local_command = {str(enable_local).lower()}
device_ssh = {str(enable_ssh).lower()}
internet_search = {str(enable_search).lower()}
current_time = true
langchain_orchestrator = true
monitoring_mcps = false
ollama_api = true

[ssh]
enabled = {str(enable_ssh).lower()}
config_path = {_quote(ssh_config_path)}
known_hosts_path = {_quote(ssh_known_hosts_path)}
"""
    config_path.write_text(text, encoding="utf-8")
    try:
        os.chmod(config_path, 0o600)
    except OSError:
        pass


def reset_runtime_state() -> None:
    """Wipe everything tied to the current install — used by the
    'forgot password' path so the operator can run setup again from scratch.

    Removes: users.json, session_secret, web_sessions/, canvas_files/,
    tool/hook/skill override files, and the rendered config.toml.
    Leaves the [paths] data_dir itself in place (it's the volume mountpoint).
    """
    config_path = get_config_file()
    data_dir = get_data_dir()
    candidates_files = [
        config_path,
        config_path.parent / "session_secret",
        config_path.parent / "ollama_api_key",
        data_dir / "users.json",
        data_dir / "tool_overrides.json",
        data_dir / "hook_overrides.json",
        data_dir / "skill_overrides.json",
    ]
    for p in candidates_files:
        try:
            p.unlink()
        except FileNotFoundError:
            pass
        except OSError:
            pass
    for sub in (data_dir / "web_sessions", data_dir / "canvas_files"):
        try:
            shutil.rmtree(sub)
        except FileNotFoundError:
            pass
        except OSError:
            pass
