#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

prompt_default() {
  local label="$1"
  local default="$2"
  local value
  read -r -p "${label} [${default}]: " value
  printf '%s' "${value:-$default}"
}

choose() {
  local label="$1"
  shift
  local options=("$@")
  local choice
  echo
  echo "$label"
  local i=1
  for option in "${options[@]}"; do
    echo "  ${i}. ${option}"
    i=$((i + 1))
  done
  while true; do
    read -r -p "Choose [1]: " choice
    choice="${choice:-1}"
    if [[ "$choice" =~ ^[0-9]+$ ]] && (( choice >= 1 && choice <= ${#options[@]} )); then
      CHOICE="$choice"
      return 0
    fi
    echo "Invalid choice."
  done
}

yaml_quote() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '"%s"' "$value"
}

ensure_bind_dir() {
  local path="$1"
  [[ "$path" == /* ]] || path="$(pwd)/$path"
  mkdir -p "$path"
}

echo "Ollama Command Deck Docker path setup"
echo "This writes docker-compose.override.yml and can recreate the web container."

app_uid="$(id -u)"
app_gid="$(id -g)"

choose "Config storage (/config: generated config, API key file, session secret)" \
  "Bind mount ./config-data (recommended)" \
  "Docker named volume ollama-hooks-config"
case "$CHOICE" in
  1)
    config_path="$(prompt_default "Config bind path" "./config-data")"
    ensure_bind_dir "$config_path"
    config_volume="$(yaml_quote "${config_path}:/config")"
    ;;
  2)
    config_volume="ollama-hooks-config:/config"
    ;;
esac

choose "Data / agent home (/data: sessions, canvas files, users, ~/.ssh)" \
  "Bind mount current user's home (recommended for SSH and host files)" \
  "Bind mount ./data" \
  "Docker named volume ollama-hooks-data" \
  "Custom bind path"
case "$CHOICE" in
  1)
    data_path="${HOME}"
    ensure_bind_dir "$data_path"
    data_volume="$(yaml_quote "${data_path}:/data")"
    ;;
  2)
    data_path="./data"
    ensure_bind_dir "$data_path"
    data_volume="$(yaml_quote "${data_path}:/data")"
    ;;
  3)
    data_volume="ollama-hooks-data:/data"
    ;;
  4)
    data_path="$(prompt_default "Data bind path" "${HOME}")"
    ensure_bind_dir "$data_path"
    data_volume="$(yaml_quote "${data_path}:/data")"
    ;;
esac

choose "Workspace (/workspace: default local-command working directory)" \
  "Bind mount ./workspace" \
  "Bind mount ~/git" \
  "Custom bind path"
case "$CHOICE" in
  1)
    workspace_path="./workspace"
    ;;
  2)
    workspace_path="${HOME}/git"
    ;;
  3)
    workspace_path="$(prompt_default "Workspace bind path" "./workspace")"
    ;;
esac
ensure_bind_dir "$workspace_path"
workspace_volume="$(yaml_quote "${workspace_path}:/workspace")"

choose "SSH access" \
  "Use /data/.ssh from the data mount" \
  "Mount host ~/.ssh read-only, including keys" \
  "Mount only host ~/.ssh/config and known_hosts read-only" \
  "No extra SSH mount"
ssh_choice="$CHOICE"
ssh_volumes=()
ssh_agent_volume=""
ssh_agent_env=""
if [[ "$ssh_choice" == "2" ]]; then
  mkdir -p "${HOME}/.ssh"
  chmod 700 "${HOME}/.ssh" || true
  ssh_volumes+=("$(yaml_quote "${HOME}/.ssh:/data/.ssh:ro")")
elif [[ "$ssh_choice" == "3" ]]; then
  mkdir -p "${HOME}/.ssh"
  touch "${HOME}/.ssh/config" "${HOME}/.ssh/known_hosts"
  chmod 700 "${HOME}/.ssh" || true
  chmod 600 "${HOME}/.ssh/config" "${HOME}/.ssh/known_hosts" || true
  ssh_volumes+=("$(yaml_quote "${HOME}/.ssh/config:/data/.ssh/config:ro")")
  ssh_volumes+=("$(yaml_quote "${HOME}/.ssh/known_hosts:/data/.ssh/known_hosts:ro")")
fi
if [[ -n "${SSH_AUTH_SOCK:-}" && -S "${SSH_AUTH_SOCK}" && "$ssh_choice" != "4" ]]; then
  ssh_agent_volume="$(yaml_quote "${SSH_AUTH_SOCK}:/ssh-agent")"
  ssh_agent_env="/ssh-agent"
fi

cat > docker-compose.override.yml <<YAML
# Generated by scripts/setup_docker_paths.sh.
# Re-run the script to change Docker mount paths.
services:
  web:
    build:
      args:
        APP_UID: "${app_uid}"
        APP_GID: "${app_gid}"
    volumes:
      - ${config_volume}
      - ${data_volume}
      - ${workspace_volume}
YAML

for volume in "${ssh_volumes[@]}"; do
  printf '      - %s\n' "$volume" >> docker-compose.override.yml
done
if [[ -n "$ssh_agent_volume" ]]; then
  printf '      - %s\n' "$ssh_agent_volume" >> docker-compose.override.yml
  cat >> docker-compose.override.yml <<YAML
    environment:
      SSH_AUTH_SOCK: "${ssh_agent_env}"
YAML
fi

cat <<'EOF'

Wrote docker-compose.override.yml

In the web setup wizard, use these in-container paths:
  SSH config path:  /data/.ssh/config
  known_hosts path: /data/.ssh/known_hosts
  work directory:   /workspace
EOF

read -r -p "Rebuild/recreate web now with ./scripts/deploy_web.sh? [Y/n]: " run_now
run_now="${run_now:-Y}"
if [[ "$run_now" =~ ^[Yy]$ ]]; then
  ./scripts/deploy_web.sh
else
  echo "Run ./scripts/deploy_web.sh when ready."
fi
